---
# tasks file for check_and_extract_server_cfg_bkp
- name: Check if file cfg-bkp*latest.tar.gz exists in the current directory
  find:
    paths: "."
    patterns: "cfg-bkp*latest.tar.gz"
  register: var_find_cfg_bkp_tarball

- name: Notify if cfg-bkp*latest.tar.gz is not found
  fail:
    msg: |
      The file cfg-bkp*latest.tar.gz is not found in the current directory
      Please download the above from below GitHub Private Repo.
      ( https://github.com/Muthukumar-Subramaniam/Scripts_by_muthu/tree/main/server/server-cfg-bkp )
  when: var_find_cfg_bkp_tarball == 0

- name: Capture exact name of cfg-bkp*latest.tar.gz
  set_fact:
    var_cfg_bkp_tarball: "{{ var_find_cfg_bkp_tarball[0].path }}"
  when: var_find_cfg_bkp_tarball > 0

- name: Extract {{ var_cfg_bkp_tarball }} to /root
  become: yes
  unarchive:
    src: "{{ var_cfg_bkp_tarball }}"
    dest: /root
  
############################## EOF ############################# 
