apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx
        image: muthu7137/muthuks-nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfs-volume
          readOnly: true
        - mountPath: /downloads
          name: cifs-volume
          readOnly: true
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc-web-share  
          readOnly: true
      - name: cifs-volume
        persistentVolumeClaim:
          claimName: cifs-pvc-downloads
          readOnly: true
