apiVersion: v1
kind: PersistentVolume
metadata:
  name: cifs-pv-downloads
spec:
  capacity:
    storage: 1Mi  # Minimal value, you can adjust this as needed
  accessModes:
    - ReadOnlyMany
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: cifs-downloads
    volumeAttributes:
      source: //server.ms.local/downloads
    nodeStageSecretRef:
      name: cifs-credentials
      namespace: default
