apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-web-share  
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi  # Minimal value to meet Kubernetes requirements
  volumeName: nfs-pv-web-share
