---
# tasks file for configure_named_service_of_server
- name: Update /etc/named.conf to Listen on {{ var_server_ip }}
  become: true
  lineinfile:
    path: /etc/named.conf
    regexp: '.*listen-on port 53 { 127.0.0.1; };.*'
    line: "listen-on port 53 { 127.0.0.1; {{ var_server_ip }}; };"
    backup: true

- name: Update allow-query with networks {{ var_network_cidr }} and {{ var_wsl_network_cidr }}
  become: true
  lineinfile:
    path: /etc/named.conf
    regexp: '.*allow-query     { localhost; };.*'
    line: "allow-query     { localhost; {{ var_network_cidr }}; {{ var_wsl_network_cidr }}; };"
    backup: true

- name: Add Google DNS servers as forwarders
  become: true
  blockinfile:
    path: /etc/named.conf
    insertafter: '.*recursion yes;.*'
    block: |

              forwarders {
                8.8.8.8;
                8.8.4.4;
              };
    backup: true

- name: Capture ms.local zone configurations from named.conf backup file
  become: true
  command: awk '/^\/\/ms\.local/{found=1} found' {{ var_cfg_bkp_dir }}/bind-dns-server-configs/named.conf 
  register: var_captured_lines_of_zones
  changed_when: false

- name: Append captured zone configurations to /etc/named.conf
  become: true
  copy:
    content: "{{ var_captured_lines_of_zones.stdout }}"
    dest: /etc/named.conf
    append: yes

- name: Copy zone files to /var/named
  become: true
  ansible.posix.synchronize:
    src: "{{ var_cfg_bkp_dir }}/bind-dns-server-configs/*ms.local*"
    dest: /var/named
    mode: push

- name: Enable and Start named service
  systemd_service:
    name: named
    state: started
    enabled: true

- name: Reload named service
  systemd_service:
    name: named
    state: reloaded

- name: Update eth0 connection profile with DNS Servers
  community.general.nmcli:
    conn_name: eth0
    type: ethernet
    dns4:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    state: present

- name: Update eth0 connection profile with DNS Search as ms.local
  community.general.nmcli:
    conn_name: eth0
    type: ethernet
    dns4_search:
      - ms.local
    state: present

########################### EOF #############################
